services:
  web_green:
    image: jaeyoungahn/linkhub:web-latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#      - DB_URL=rds-endpoint
#      - DB_USERNAME=username
#      - DB_PASSWORD=password
    expose:
      - "8080"

  web_blue:
    image: jaeyoungahn/linkhub:web-latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#      - DB_URL=rds-endpoint
#      - DB_USERNAME=username
#      - DB_PASSWORD=password
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.link-hub.site/fullchain.pem:/etc/letsencrypt/live/api.link-hub.site/fullchain.pem
      - /etc/letsencrypt/live/api.link-hub.site/privkey.pem:/etc/letsencrypt/live/api.link-hub.site/privkey.pem