name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t jaeyoungahn/linkhub:${GITHUB_REF#refs/tags/} .
          docker tag jaeyoungahn/linkhub:${GITHUB_RUN_NUMBER} jaeyoungahn/linkhub:latest
          docker push jaeyoungahn/linkhub:${GITHUB_RUN_NUMBER}
          docker push jaeyoungahn/linkhub:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x deploy.sh
            ./deploy.sh